# NumPy Part-1

In [ ]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print (arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
a = np.array([20,30,40])
b = np.array([10,20,50])
# Sum
print(a+b)
#Multiply
print(a*b)

[30 50 90]
[ 200  600 2000]


In [5]:
arr = np.array((1, 2, 3, 4, 5))
print (arr)
print (type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Demension in Array 

In [6]:
arr = np.array(20)
print (arr)
print (type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


# 1D array 

In [7]:
arr = np.array([1, 2, 3 , 4, 5, 6])
print (arr)
print (arr.ndim)

[1 2 3 4 5 6]
1


# 2D Array 

In [8]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print (arr)
print (arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [9]:
arr = np.array([[1.1 , 2.2, 3.3], [4.4, 5.5, 6.6] ])
print(arr)
print (arr.ndim)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
2


# 3D Array 

In [10]:
arr= np.array([[[1, 2, 3],[4,5,6]], [[1, 2, 3], [4, 5, 6]]] )
print (arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


# 0 , 1, 2, 3 Dimension in fram 

In [11]:
a = np.array(42)
b = np.array([1, 2, 3 ,4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4,5, 6]] , [[1, 2, 3],[4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimension Array 

In [12]:
arr = np.array([1, 2, 3, 4],ndmin = 5)
print (arr)
print ('number of dimensions : ',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions :  5


In [13]:
a = np.array([[[[[1, 2, 3, 4, 5]]]]])
print(a)
print(a.ndim)

[[[[[1 2 3 4 5]]]]]
5


# Numpy Array Indexing 

# Get the first element from the following arrays & Add them

In [14]:
arr = np.array([1, 2 , 3, 4 ])
print (arr[0])

1


# Get third and sixth and 8th elements from the following arrays and add them .

In [15]:
m = np.array ([41, 87, 34, 56, 8, 39 , 23, 90, 15, 10 , 19 , 56])
print("the secoond element is ", m[2])
print("the sixth element is ", m[5])
print("the 8th element is ", m[7])
print("sum of these elements are ", m[2]+m[5]+m[7])

the secoond element is  34
the sixth element is  39
the 8th element is  90
sum of these elements are  163


# Access 2 D array 

In [18]:
arr = np.array([[10 , 20 , 30 , 40 , 50 ] , [60, 70 , 80 , 90, 100]])
print ('2nd element on 1st row: ',arr[0, 1])

2nd element on 1st row:  20


In [19]:
arr = np.array([[10 , 20 , 30 , 40 , 50 ] , [60, 70 , 80 , 90, 100]])
print ('1nd element on 2nd row: ',arr[1, 0])

1nd element on 2nd row:  60


In [21]:
arr = np.array([[10 , 20 , 30 , 40 , 50 ] , [60, 70 , 80 , 90, 100]])
print('4th element on 1nd row is', arr[0,3])

4th element on 1nd row is 40


In [22]:
arr = np.array([[10 , 20 , 30 , 40 , 50 ] , [60, 70 , 80 , 90, 100]])
print('1st element on 1nd row is', arr[1,0])

1st element on 1nd row is 60


In [23]:
arr = np.array([[10 , 20 , 30 , 40 , 50 ] , [60, 70 , 80 , 90, 100]])
print('last element on 2nd row is', arr[1,4])

last element on 2nd row is 100


# Add the first element of the row 1 and last element 

In [25]:
arr = np.array([[10 , 20 , 30 , 40 , 50 ] , [60, 70 , 80 , 90, 100]])

print ('First element of 1st row:', arr[0,0])
print('last element on 2nd row is', arr[1,4])
print("Sum is ", arr[0,0]+arr[1,4])

First element of 1st row: 10
last element on 2nd row is 100
Sum is  110


# Access 3-D array 

# Accsess the third element of the second array of the first array 

In [26]:
arr = np.array([[[1, 2, 3], [4,5,6]] , [[7, 8 , 9], [10,11,12]]])
print (arr[0,1,2])

6


In [27]:
arr = np.array([[[1, 2, 3], [4,5,6]] , [[7, 8 , 9], [10,11,12]]])
print(arr[1,1,2])

12


In [28]:
arr =np.array([1,2,3,4,5,6,7])
print (arr[::2]) # Skipping 1 index every time 

[1 3 5 7]


In [29]:
a = np.array([[10,20,30,40,50] , [60,70,80,90,100]])
print (a[0,0:4])

[10 20 30 40]


# Cecking the Data type of an Array 

In [31]:
arr =np.array([1,2,3,4])
print (arr.dtype)

int32


In [32]:
arr = np.array(['Hira','jira','Sohag'])
print(arr.dtype)

<U5


# Creating array with a defined Data Type

In [33]:
arr = np.array([1,2,3,4],dtype='S')
print (arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [34]:
arr = np.array([1,2,3,4],dtype ='i4')
print (arr)
print(arr.dtype)

[1 2 3 4]
int32


# Numpy Array Shape

# print the shape of a 2D array 

In [36]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print (arr.shape)

(2, 4)


In [37]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])
print (arr.shape)

(1, 3, 4)


# Joining Numpy Arrays

In [38]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr =np.concatenate((arr1,arr2))
print (arr)

[1 2 3 4 5 6]


# Join 2D array 

In [39]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr =np.concatenate((arr1,arr2), axis =1)
print (arr)

[[1 2 5 6]
 [3 4 7 8]]


In [41]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr =np.concatenate((arr1,arr2), axis =0)
print (arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting Numpy Arrays

In [42]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)
print (newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# Splititng array in 4 parts

In [43]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)
print (newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Ravel and Flatten

In [45]:
m = np.array([[[1, 2, 3] , [4,5,6], [7,8,9]]])
print (m)
print("Dimension is ",m.ndim)

n=m.ravel()
print(n)
print("Now the new Dimenssion is",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is  3
[1 2 3 4 5 6 7 8 9]
Now the new Dimenssion is 1


In [46]:
m = np.array([[[1, 2, 3] , [4,5,6], [7,8,9]]])
print (m)
print("Dimension is ",m.ndim)

n=m.flatten()
print(n)
print("Now the new Dimenssion is",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is  3
[1 2 3 4 5 6 7 8 9]
Now the new Dimenssion is 1


In [47]:
c= np.array([[[[1,2,3] ,[78,89,25],[45,26,84]]]])
print(c)
print ("The dimension is",c.ndim)
d=c.ravel()
print (d)
print("Now the new Dimension is",d.ndim)

[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]
The dimension is 4
[ 1  2  3 78 89 25 45 26 84]
Now the new Dimension is 1


# Uniqe Funciton

In [48]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x= np.unique(k)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
[ 1  2  3  4  5  6  7  9 12 22 33]


In [49]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x= np.unique(k , return_index = True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64))


In [50]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x= np.unique(k , return_index = True , return_counts = True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64), array([2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1], dtype=int64))
